version: '3.5'

services:
  postgres:
    container_name: pgsandbox_postgres
    image: postgres
    environment:
      POSTGRES_DB: sandbox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
       # - postgres-sandbox:/data/postgres
       - ./scripts/:/scripts/
    ports:
      - "5432:5432"
    networks:
      - pgsandbox
    restart: unless-stopped

  pgadmin:
    container_name: pgsandbox_pgadmin
    image: dpage/pgadmin4
    entrypoint: >
      /bin/sh -c "
      cp -f /pgadmin4/pgpass /var/lib/pgadmin/;
      chmod 600 /var/lib/pgadmin/pgpass;
      chown pgadmin:root /var/lib/pgadmin/pgpass;
      /entrypoint.sh
      "
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
       - ./pgadmin/pgpass:/pgadmin4/pgpass
       - ./pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - pgsandbox
    restart: unless-stopped

networks:
  pgsandbox: